name: encontre_sua_crianca
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  universal_html: ^2.2.4
  url_launcher: ^6.2.6
  map_location_picker: ^1.2.8+3
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/