// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvqYPosCyazBnIs3h6iUOHnRVXdKDtD0k',
    appId: '1:930015899592:web:ec7735f4b8510305a69afd',
    messagingSenderId: '930015899592',
    projectId: 'achamossuacrianca',
    authDomain: 'achamossuacrianca.firebaseapp.com',
    storageBucket: 'achamossuacrianca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCln63HV63x9JFxriJA-WxHwg0R1tLNuPE',
    appId: '1:930015899592:android:41eb32abe1459aa4a69afd',
    messagingSenderId: '930015899592',
    projectId: 'achamossuacrianca',
    storageBucket: 'achamossuacrianca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr4Vnns5FrRiN36auTr03urHuHbYGqWGw',
    appId: '1:930015899592:ios:909b28718a93aa4da69afd',
    messagingSenderId: '930015899592',
    projectId: 'achamossuacrianca',
    storageBucket: 'achamossuacrianca.appspot.com',
    iosBundleId: 'com.example.encontreSuaCrianca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvqYPosCyazBnIs3h6iUOHnRVXdKDtD0k',
    appId: '1:930015899592:web:a1ef20d48658242fa69afd',
    messagingSenderId: '930015899592',
    projectId: 'achamossuacrianca',
    authDomain: 'achamossuacrianca.firebaseapp.com',
    storageBucket: 'achamossuacrianca.appspot.com',
  );
}
